development:
  adapter: postgresql

test:
  adapter: test

production:
  adapter: postgresql
  url: ENV.fetch("POSTGRES_HOST")

# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: finejoke_production
